import { MonitoringZone } from "../types";

export const monitoringZones: MonitoringZone[] = [
  // Musi River Zones (12 zones)
  {
    id: "zone-musi-01",
    riverId: "river-musi",
    name: "Zone 01 - Osman Sagar",
    latitude: 17.385,
    longitude: 78.342,
    pollutionLevel: 25,
    waterQualityScore: 78,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-01",
    recommendedAction: "Regular monitoring",
  },
  {
    id: "zone-musi-02",
    riverId: "river-musi",
    name: "Zone 02 - Himayat Sagar",
    latitude: 17.398,
    longitude: 78.365,
    pollutionLevel: 35,
    waterQualityScore: 72,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-02",
    recommendedAction: "Continue monitoring",
  },
  {
    id: "zone-musi-03",
    riverId: "river-musi",
    name: "Zone 03 - Mehdipatnam",
    latitude: 17.412,
    longitude: 78.388,
    pollutionLevel: 45,
    waterQualityScore: 65,
    primaryWaste: "Domestic",
    riskLevel: "Medium",
    lastInspection: "2026-09-03",
    recommendedAction: "Increase sampling frequency",
  },
  {
    id: "zone-musi-04",
    riverId: "river-musi",
    name: "Zone 04 - Mozamjahi Market",
    latitude: 17.425,
    longitude: 78.412,
    pollutionLevel: 78,
    waterQualityScore: 42,
    primaryWaste: "Plastic + Sewage",
    riskLevel: "High",
    lastInspection: "2026-09-04",
    recommendedAction: "Immediate cleanup required",
  },
  {
    id: "zone-musi-05",
    riverId: "river-musi",
    name: "Zone 05 - Abids",
    latitude: 17.438,
    longitude: 78.435,
    pollutionLevel: 52,
    waterQualityScore: 58,
    primaryWaste: "Mixed",
    riskLevel: "Medium",
    lastInspection: "2026-09-05",
    recommendedAction: "Monitor and plan cleanup",
  },
  {
    id: "zone-musi-06",
    riverId: "river-musi",
    name: "Zone 06 - Koti",
    latitude: 17.452,
    longitude: 78.458,
    pollutionLevel: 48,
    waterQualityScore: 62,
    primaryWaste: "Domestic",
    riskLevel: "Medium",
    lastInspection: "2026-09-06",
    recommendedAction: "Regular monitoring",
  },
  {
    id: "zone-musi-07",
    riverId: "river-musi",
    name: "Zone 07 - Dabirpur",
    latitude: 17.465,
    longitude: 78.482,
    pollutionLevel: 75,
    waterQualityScore: 48,
    primaryWaste: "Industrial Waste",
    riskLevel: "High",
    lastInspection: "2026-09-07",
    recommendedAction: "Investigate industrial sources",
  },
  {
    id: "zone-musi-08",
    riverId: "river-musi",
    name: "Zone 08 - Nala.Nullah",
    latitude: 17.478,
    longitude: 78.505,
    pollutionLevel: 55,
    waterQualityScore: 55,
    primaryWaste: "Sewage",
    riskLevel: "Medium",
    lastInspection: "2026-09-08",
    recommendedAction: "Monitor sewage inflow",
  },
  {
    id: "zone-musi-09",
    riverId: "river-musi",
    name: "Zone 09 - Nagole",
    latitude: 17.492,
    longitude: 78.528,
    pollutionLevel: 42,
    waterQualityScore: 68,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-09",
    recommendedAction: "Continue monitoring",
  },
  {
    id: "zone-musi-10",
    riverId: "river-musi",
    name: "Zone 10 - LB Nagar",
    latitude: 17.505,
    longitude: 78.552,
    pollutionLevel: 38,
    waterQualityScore: 70,
    primaryWaste: "Mixed",
    riskLevel: "Low",
    lastInspection: "2026-09-10",
    recommendedAction: "Regular monitoring",
  },
  {
    id: "zone-musi-11",
    riverId: "river-musi",
    name: "Zone 11 - Hayathnagar",
    latitude: 17.518,
    longitude: 78.575,
    pollutionLevel: 48,
    waterQualityScore: 62,
    primaryWaste: "Agricultural",
    riskLevel: "Medium",
    lastInspection: "2026-09-11",
    recommendedAction: "Monitor agricultural runoff",
  },
  {
    id: "zone-musi-12",
    riverId: "river-musi",
    name: "Zone 12 - Musi Confluence",
    latitude: 17.532,
    longitude: 78.598,
    pollutionLevel: 40,
    waterQualityScore: 65,
    primaryWaste: "Mixed",
    riskLevel: "Medium",
    lastInspection: "2026-09-12",
    recommendedAction: "Regular monitoring",
  },

  // Ganga River Zones (5 zones)
  {
    id: "zone-ganga-01",
    riverId: "river-ganga",
    name: "Ganga Zone 01 - Haridwar",
    latitude: 29.945,
    longitude: 78.163,
    pollutionLevel: 35,
    waterQualityScore: 68,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-05",
    recommendedAction: "Maintain water quality",
  },
  {
    id: "zone-ganga-02",
    riverId: "river-ganga",
    name: "Ganga Zone 02 - Rishikesh",
    latitude: 30.087,
    longitude: 78.269,
    pollutionLevel: 28,
    waterQualityScore: 75,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-06",
    recommendedAction: "Continue monitoring",
  },
  {
    id: "zone-ganga-03",
    riverId: "river-ganga",
    name: "Ganga Zone 03 - Kanpur",
    latitude: 26.449,
    longitude: 80.332,
    pollutionLevel: 72,
    waterQualityScore: 42,
    primaryWaste: "Industrial",
    riskLevel: "High",
    lastInspection: "2026-09-07",
    recommendedAction: "Investigate industrial discharge",
  },
  {
    id: "zone-ganga-04",
    riverId: "river-ganga",
    name: "Ganga Zone 04 - Varanasi",
    latitude: 25.318,
    longitude: 83.009,
    pollutionLevel: 58,
    waterQualityScore: 52,
    primaryWaste: "Domestic Sewage",
    riskLevel: "Medium",
    lastInspection: "2026-09-08",
    recommendedAction: "Improve sewage treatment",
  },
  {
    id: "zone-ganga-05",
    riverId: "river-ganga",
    name: "Ganga Zone 05 - Patna",
    latitude: 25.609,
    longitude: 85.138,
    pollutionLevel: 62,
    waterQualityScore: 48,
    primaryWaste: "Mixed",
    riskLevel: "Medium",
    lastInspection: "2026-09-09",
    recommendedAction: "Comprehensive monitoring",
  },

  // Yamuna River Zones (4 zones)
  {
    id: "zone-yamuna-01",
    riverId: "river-yamuna",
    name: "Yamuna Zone 01 - Yamunotri",
    latitude: 30.998,
    longitude: 78.464,
    pollutionLevel: 15,
    waterQualityScore: 85,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-03",
    recommendedAction: "Maintain pristine condition",
  },
  {
    id: "zone-yamuna-02",
    riverId: "river-yamuna",
    name: "Yamuna Zone 02 - Delhi",
    latitude: 28.614,
    longitude: 77.209,
    pollutionLevel: 82,
    waterQualityScore: 35,
    primaryWaste: "Sewage + Industrial",
    riskLevel: "Critical",
    lastInspection: "2026-09-04",
    recommendedAction: "Emergency intervention required",
  },
  {
    id: "zone-yamuna-03",
    riverId: "river-yamuna",
    name: "Yamuna Zone 03 - Agra",
    latitude: 27.177,
    longitude: 78.019,
    pollutionLevel: 65,
    waterQualityScore: 45,
    primaryWaste: "Domestic",
    riskLevel: "High",
    lastInspection: "2026-09-05",
    recommendedAction: "Increase sewage treatment capacity",
  },
  {
    id: "zone-yamuna-04",
    riverId: "river-yamuna",
    name: "Yamuna Zone 04 - Allahabad",
    latitude: 25.436,
    longitude: 81.847,
    pollutionLevel: 48,
    waterQualityScore: 58,
    primaryWaste: "Mixed",
    riskLevel: "Medium",
    lastInspection: "2026-09-06",
    recommendedAction: "Monitor confluence with Ganga",
  },

  // Godavari River Zones (4 zones)
  {
    id: "zone-godavari-01",
    riverId: "river-godavari",
    name: "Godavari Zone 01 - Nasik",
    latitude: 19.997,
    longitude: 73.789,
    pollutionLevel: 42,
    waterQualityScore: 62,
    primaryWaste: "Domestic",
    riskLevel: "Medium",
    lastInspection: "2026-09-04",
    recommendedAction: "Monitor urban runoff",
  },
  {
    id: "zone-godavari-02",
    riverId: "river-godavari",
    name: "Godavari Zone 02 - Rajahmundry",
    latitude: 17.004,
    longitude: 81.797,
    pollutionLevel: 55,
    waterQualityScore: 55,
    primaryWaste: "Industrial",
    riskLevel: "Medium",
    lastInspection: "2026-09-05",
    recommendedAction: "Check industrial compliance",
  },
  {
    id: "zone-godavari-03",
    riverId: "river-godavari",
    name: "Godavari Zone 03 - Kakinada",
    latitude: 16.989,
    longitude: 82.247,
    pollutionLevel: 38,
    waterQualityScore: 68,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-06",
    recommendedAction: "Continue monitoring",
  },
  {
    id: "zone-godavari-04",
    riverId: "river-godavari",
    name: "Godavari Zone 04 - Dowleswaram",
    latitude: 16.917,
    longitude: 81.634,
    pollutionLevel: 45,
    waterQualityScore: 60,
    primaryWaste: "Agricultural",
    riskLevel: "Medium",
    lastInspection: "2026-09-07",
    recommendedAction: "Monitor agricultural runoff",
  },

  // Krishna River Zones (4 zones)
  {
    id: "zone-krishna-01",
    riverId: "river-krishna",
    name: "Krishna Zone 01 - Mahabaleshwar",
    latitude: 17.927,
    longitude: 73.657,
    pollutionLevel: 18,
    waterQualityScore: 82,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-05",
    recommendedAction: "Maintain water quality",
  },
  {
    id: "zone-krishna-02",
    riverId: "river-krishna",
    name: "Krishna Zone 02 - Satara",
    latitude: 17.686,
    longitude: 74.009,
    pollutionLevel: 32,
    waterQualityScore: 72,
    primaryWaste: "Agricultural",
    riskLevel: "Low",
    lastInspection: "2026-09-06",
    recommendedAction: "Monitor irrigation runoff",
  },
  {
    id: "zone-krishna-03",
    riverId: "river-krishna",
    name: "Krishna Zone 03 - Vijayawada",
    latitude: 16.506,
    longitude: 80.648,
    pollutionLevel: 58,
    waterQualityScore: 52,
    primaryWaste: "Domestic Sewage",
    riskLevel: "Medium",
    lastInspection: "2026-09-07",
    recommendedAction: "Improve sewage treatment",
  },
  {
    id: "zone-krishna-04",
    riverId: "river-krishna",
    name: "Krishna Zone 04 - Machilipatnam",
    latitude: 16.186,
    longitude: 81.134,
    pollutionLevel: 42,
    waterQualityScore: 62,
    primaryWaste: "Mixed",
    riskLevel: "Medium",
    lastInspection: "2026-09-08",
    recommendedAction: "Comprehensive monitoring",
  },

  // Brahmaputra River Zones (4 zones)
  {
    id: "zone-brahmaputra-01",
    riverId: "river-brahmaputra",
    name: "Brahmaputra Zone 01 - Pasighat",
    latitude: 28.067,
    longitude: 95.330,
    pollutionLevel: 12,
    waterQualityScore: 88,
    primaryWaste: "Organic",
    riskLevel: "Low",
    lastInspection: "2026-09-04",
    recommendedAction: "Maintain pristine condition",
  },
  {
    id: "zone-brahmaputra-02",
    riverId: "river-brahmaputra",
    name: "Brahmaputra Zone 02 - Dibrugarh",
    latitude: 27.473,
    longitude: 94.913,
    pollutionLevel: 32,
    waterQualityScore: 72,
    primaryWaste: "Industrial",
    riskLevel: "Low",
    lastInspection: "2026-09-05",
    recommendedAction: "Monitor tea estate runoff",
  },
  {
    id: "zone-brahmaputra-03",
    riverId: "river-brahmaputra",
    name: "Brahmaputra Zone 03 - Tezpur",
    latitude: 26.653,
    longitude: 92.785,
    pollutionLevel: 38,
    waterQualityScore: 68,
    primaryWaste: "Domestic",
    riskLevel: "Low",
    lastInspection: "2026-09-06",
    recommendedAction: "Continue monitoring",
  },
  {
    id: "zone-brahmaputra-04",
    riverId: "river-brahmaputra",
    name: "Brahmaputra Zone 04 - Guwahati",
    latitude: 26.144,
    longitude: 91.736,
    pollutionLevel: 52,
    waterQualityScore: 58,
    primaryWaste: "Mixed",
    riskLevel: "Medium",
    lastInspection: "2026-09-07",
    recommendedAction: "Increase urban waste management",
  },
];

export function getZonesByRiver(riverId: string): MonitoringZone[] {
  return monitoringZones.filter((zone) => zone.riverId === riverId);
}

export function getZoneById(id: string): MonitoringZone | undefined {
  return monitoringZones.find((zone) => zone.id === id);
}
